# Welcome to Jekyll!
title: Pirati Praha 8
email: info@pirati.cz
description: >- # this means to ignore newlines until "baseurl:"
  Česká pirátská strana - místní sdružení na Praze 8
url: "" # the base hostname & protocol for your site, e.g. http://example.com
keywords: piráti, česká pirátská strana, svoboda, demokracie, pirati na osmičce # dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku

#administrator:
#    email: jmeno.prijmeni@pirati.cz # mail kam pujdou maily o webu

organization:
  name: "<b>Praha 8</b>, místní sdružení"
  short_name: "Piráti Praha 8"
  email: praha8@pirati.cz
  #phone: +420 777 123 456 789
  address: |
      Na Moráni 3
      120 00 Praha 2
  mapLink: https://mapy.cz/zakladni?x=14.4151543&y=50.0733415&z=18&source=addr&id=9018965&q=Na%20Mor%C3%A1ni%203
  residenceImg:
  mapLink: https://mapy.cz/s/2N7Yv
  redmineLink: https://redmine.pirati.cz/projects

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: piratiRootWebsite
  - type: custom
    iconClass: fa fa-facebook
    label: Facebook
    body: <a href="https://www.facebook.com/piratipraha8" target="_blank">Piráti Praha 8</a>


calendar:
  apiKey: AIzaSyBdjZxz4r9lPyD3CiSxQa6G3mf47ezI7Ks
  id: rm0h4oqjk2j2o0615sc4d1slfk@group.calendar.google.com
  title: "Kalendář Pirátů Prahy 8"
  page: "https://calendar.google.com/calendar/embed?mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=npabehj0rpaqtgo960ju2vjq2s%40group.calendar.google.com&amp;color=%238D6F47&amp;ctz=Europe%2FPrague"

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/piratipraha8/"
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/praha8.pirati.cz/
  branch: master


############### SETTINSG #################

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass
# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor


permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby-2018/:path/
  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: 
        - foto
        - personContact
        - people
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: 
         - garant
         - program

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.2.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
